image: Ubuntu
stack: jdk 11
build_script:
- mvn install
cache:
- /home/appveyor/.m2/repository/ -> pom.xml
artifacts:
  - path: target/product-file-mapper-1.0-SNAPSHOT.jar
    name: ProductFileMapper 1.0 Snapshot